### ISSUE TITLE
接口api访问失败

### ISSUE THREAD

**Issue by tjpulord** [LiangLuDev/WeYueReader#14]
www.luliangdev.cn/api/

app-type:Android
access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiOTUyOCIsImlhdCI6MTUyNTg0MTE3OSwiZXhwIjoxNTI4NDMzMTc5fQ.WFVaErTIG7mXtZdhpkdCf2P947b9xHucbwcQoDzdrbE

报错信息：
<h1>Not Found</h1>
<h2>404</h2>
<pre>Error: Not Found
    at /node/node_dev/WeYueSever/app.js:41:15
    at Layer.handle [as handle_request] (/node/node_dev/WeYueSever/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node/node_dev/WeYueSever/node_modules/express/lib/router/index.js:317:13)
    at /node/node_dev/WeYueSever/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/node/node_dev/WeYueSever/node_modules/express/lib/router/index.js:335:12)
    at next (/node/node_dev/WeYueSever/node_modules/express/lib/router/index.js:275:10)
    at /node/node_dev/WeYueSever/node_modules/express/lib/router/index.js:635:15
    at next (/node/node_dev/WeYueSever/node_modules/express/lib/router/index.js:260:14)
    at jwt.verify (/node/node_dev/WeYueSever/controller/api/headers.js:33:17)
    at /node/node_dev/WeYueSever/node_modules/jsonwebtoken/verify.js:27:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)</pre>

登录用户名 9528 密码123456

**Comment by LiangLuDev** [comment]
@tjpulord 可能服务器抽风 现在应该可以

**Comment by tjpulord** [comment]
@LiangLuDev 又试了下，还是不行，依然报错

**Comment by LiangLuDev** [comment]
@tjpulord 
![image](https://user-images.githubusercontent.com/16227011/39862308-fbc9d538-5475-11e8-8b6c-7bf1b8daccb0.png)

**Comment by LiangLuDev** [comment]
这样操作了吗
