### ISSUE TITLE
错误~

### ISSUE THREAD

**Issue by ylmyg** [LiangLuDev/WeYueReader#15]
FATAL EXCEPTION: main
                                                                   Process: com.lianglu.weyue, PID: 26258
                                                                   io.reactivex.exceptions.OnErrorNotImplementedException: Can not perform this action after onSaveInstanceState
                                                                       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                       at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
                                                                       at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
                                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:262)
                                                                       at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:559)
                                                                       at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:113)
                                                                       at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver$InnerObserver.onNext(ObservableConcatMap.java:250)
                                                                       at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:265)
                                                                       at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:184)
                                                                       at com.tbruyelle.rxpermissions2.RxPermissionsFragment.onRequestPermissionsResult(RxPermissionsFragment.java:64)
                                                                       at com.tbruyelle.rxpermissions2.RxPermissionsFragment.onRequestPermissionsResult(RxPermissionsFragment.java:49)
                                                                       at android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:6738)
                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:6610)
                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3774)
                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3821)
                                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:168)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:150)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5659)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
                                                                    Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
                                                                       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
                                                                       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
                                                                       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
                                                                       at com.lianglu.weyue.view.activity.impl.MainActivity.switchFragment(MainActivity.java:238)
                                                                       at com.lianglu.weyue.view.activity.impl.MainActivity.lambda$null$2$MainActivity(MainActivity.java:133)
                                                                       at com.lianglu.weyue.view.activity.impl.MainActivity$$Lambda$3.accept(Unknown Source)

第一次安装APP，手机没有内置SD卡，当点击扫描书籍，确定开启读取SD卡权限，报错，程序退出

**Comment by LiangLuDev** [comment]
@ylmyg  谢谢反馈  我这边看一下问题
