### ISSUE TITLE
我clone了项目然后把项目导入android studio，编译没问题，运行的时候报了下面这个错误

### ISSUE THREAD

**Issue by liforgit** [LiangLuDev/WeYueReader#2]
尝试了一下网上的方法，问题没解决，请教一下大佬这个问题怎么破？)

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.lianglu.weyue, PID: 30142
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lianglu.weyue/com.lianglu.weyue.view.activity.impl.MainActivity}: **android.content.res.Resources$NotFoundException: File res/drawable/ic_setting.xml from drawable resource ID #0x7f08009f**
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                      at android.app.ActivityThread.access$800(ActivityThread.java:141)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5052)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                      at dalvik.system.NativeStart.main(Native Method)
                   **Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_setting.xml from drawable resource ID #0x7f08009f**
                      at android.content.res.Resources.loadDrawable(Resources.java:2139)
                      at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:394)
                      at android.content.res.Resources.loadDrawable(Resources.java:2062)
                      at android.content.res.Resources.getDrawable(Resources.java:710)
                      **at com.lianglu.weyue.utils.BaseUtils.setIconDrawable(BaseUtils.java:30)
                      at com.lianglu.weyue.view.activity.impl.MainActivity.initMenu(MainActivity.java:119)**

**Comment by LiangLuDev** [comment]
@liforgit 应该是版本的问题，你手机什么版本  我这边看一下问题

**Comment by liforgit** [comment]
手机API是19的

**Comment by liforgit** [comment]
的确是手机版本问题，我在API24的模拟器上能运行

**Comment by LiangLuDev** [comment]
@liforgit 对的 ，好像有兼容方案 我忘了  你可以查查

**Comment by liforgit** [comment]
好，多谢了 :)
