### ISSUE TITLE
刚装的打开直接崩溃

### ISSUE THREAD

**Issue by stevefat** [LiangLuDev/WeYueReader#4]
java.lang.RuntimeException: Font asset not found fonts/typeface.otf

**Comment by LiangLuDev** [comment]
@stevefat 你好  是
![image](https://user-images.githubusercontent.com/16227011/39104418-0908d140-46e3-11e8-8d28-ff180ce079c0.png) 这个版本吗 。我早上更新了一版，如果还是这样  你提供一下手机型号和手机版本号，谢谢

**Comment by yangpengliao** [comment]
我也是安装打开就奔溃，主页都还没看到     锤子m1  6.0

**Comment by LiangLuDev** [comment]
@yangpengliao 可以看到异常吗  你可以连上Android studio看看异常  反馈给我。我后面加上崩溃统计

**Comment by yangpengliao** [comment]
E/RxHttpUtils: {"code":60002,"msg":"token无效,请重新登录"}

 E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.lianglu.weyue, PID: 6536
                                                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
                                                     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5547)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
                                                  Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                     at android.app.ContextImpl.startActivity(ContextImpl.java:687)
                                                     at android.app.ContextImpl.startActivity(ContextImpl.java:674)
                                                     at android.content.ContextWrapper.startActivity(ContextWrapper.java:333)
                                                     at com.lianglu.weyue.utils.rxhelper.RxObserver.doOnNext(RxObserver.java:76)
                                                     at com.allen.library.base.BaseDataObserver.onNext(BaseDataObserver.java:27)
                                                     at com.allen.library.base.BaseDataObserver.onNext(BaseDataObserver.java:18)
                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5547) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

**Comment by LiangLuDev** [comment]
@yangpengliao 重新下载一下试试
https://fir.im/dlrn
