### ISSUE TITLE
网络异常

### ISSUE THREAD

**Issue by JustinNick** [LiangLuDev/WeYueReader#6]
什么玩意，一直提示网络异常，我可是100兆的网啊，

**Comment by JustinNick** [comment]
改为!BuildConfig.DEBUG时，直接运行闪退

**Comment by LiangLuDev** [comment]
@JustinNick 你是clone项目的跑的吗？报什么错

**Comment by JustinNick** [comment]
Process: com.lianglu.weyue, PID: 8743
                                                                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
                                                                     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
                                                                     at android.os.Handler.handleCallback(Handler.java:743)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:150)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                  Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                                     at android.app.ContextImpl.startActivity(ContextImpl.java:757)
                                                                     at android.app.ContextImpl.startActivity(ContextImpl.java:737)
                                                                     at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
                                                                     at com.lianglu.weyue.utils.rxhelper.RxObserver.doOnNext(RxObserver.java:76)
                                                                     at com.allen.library.base.BaseDataObserver.onNext(BaseDataObserver.java:27)
                                                                     at com.allen.library.base.BaseDataObserver.onNext(BaseDataObserver.java:18)
                                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                     at android.os.Handler.handleCallback(Handler.java:743) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:150) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by LiangLuDev** [comment]
@JustinNick 你qq多少  我加你

**Comment by JustinNick** [comment]
发你了，收到没？

**Comment by LiangLuDev** [comment]
@JustinNick 你看一下这个文件是不是这样写的    我没有收到啊 你加我吧  927195249

**Comment by liudaohong** [comment]
接口  不能用了吗

**Comment by LiangLuDev** [comment]
@liudaohong 
![image](https://user-images.githubusercontent.com/16227011/39232067-b3368754-489e-11e8-8ba9-e1b248b6e919.png)
